name: DAST
on:
  push:

jobs:
  test-dast:
    name: test-dast
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install dependencies # install make to run the Makefile
        run: |
          sudo apt-get install make
      - name: Install project
        run: |
          ./configure
          make
          make install
      - name: Run Dastardly Action Step
        uses: PortSwigger/dastardly-github-action@main
        with:
          target-url: 'https://localhost:8000/'
      - name: Publish Test Report
        if: always()                                    # Forces this step to always run
        uses: mikepenz/action-junit-report@v3
        with:
          report_paths: '**/dastardly-report.xml'       # You need to update this path if you pass in a different output filename to the Dastardly action
          require_tests: true